language: node_js

node_js:
  - "8"
  - "10"
  - "12"
  
install:
  - yarn install
  - yarn global add codecov

script: 'true'

#script:
#  - node --harmony ./node_modules/.bin/istanbul cover ./node_modules/mocha/bin/_mocha --reporter test -- -R spec
#  - codecov
